[server]
bind_host = "127.0.0.1"
bind_port = 56789
max_connections = 100

[proxy]
proxy_file = "proxies.txt"
test_timeout = 5
health_check_interval = 300 # 健康检测间隔(秒)
retry_times = 3
auto_switch = false        # 是否开启自动切换代理
switch_interval = 5      # 自动切换间隔(秒)

[log]
show_connection_log = false  # 设置为 false 可以关闭连接日志
show_error_log = false      # 设置为 false 可以关闭错误日志