[server]
bind_host = "127.0.0.1"
bind_port = 1080
max_connections = 100

[proxy]
proxy_file = "proxies.txt"
test_timeout = 5
health_check_interval = 300 # 健康检测间隔(秒)
retry_times = 3
auto_switch = false        # 是否开启自动切换代理
switch_interval = 5      # 自动切换间隔(秒)
max_concurrency = 100     # 最大并发测试数

[log]
show_connection_log = false  # 设置为 false 可以关闭连接日志
show_error_log = false      # 设置为 false 可以关闭错误日志

[fofa]
switch = false
api_url = 'https://fofa.info/api/v1/search/all'
fofa_key = '186******f8a******6a92******4abf1c' # 替换成自己的key
query_str = '(protocol=="socks5" && country="CN" && banner="Method:No Authentication") && after="2025-02-25"' # 这里可以用after添加时间限制，过滤不可用的代理
size = 10000 # 这里是获取的条数

[quake]
switch = false
api_url = 'https://quake.360.net/api/v3/search/quake_service'
quake_key = '0e****-3***-4***-a***-5a21********' # 替换成自己的key
query_str = 'service:socks5 AND country: "CN" AND response:"No authentication"'
size = 500 # 这里是获取的条数

[hunter]
switch = false
api_url = 'https://hunter.qianxin.com/openApi/search'
hunter_key = '365*******9ab9*******b0f0*******d1cd0d3399' # 替换成自己的key
query_str = 'protocol=="socks5"&&protocol.banner="No authentication"&&ip.country="CN"'
size = 4 # 这里是指页数，一页100条
