name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build-linux:
    name: 构建Linux二进制文件
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 安装必要依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools musl-dev linux-libc-dev
          
      - name: 安装Rust工具链
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      
      - name: 创建缺失的头文件
        run: |
          sudo mkdir -p /usr/local/musl/include/linux
          sudo tee /usr/local/musl/include/linux/mman.h > /dev/null << 'EOF'
          /* 最小化的mman.h头文件 */
          #ifndef _LINUX_MMAN_H
          #define _LINUX_MMAN_H
          
          #define PROT_READ      0x1
          #define PROT_WRITE     0x2
          #define PROT_EXEC      0x4
          #define PROT_NONE      0x0
          
          #define MAP_SHARED     0x01
          #define MAP_PRIVATE    0x02
          #define MAP_FIXED      0x10
          #define MAP_ANONYMOUS  0x20
          
          #define MADV_DONTFORK  0x10
          
          #endif /* _LINUX_MMAN_H */
          EOF
      
      - name: 编译musl兼容的OpenSSL
        run: |
          wget https://www.openssl.org/source/openssl-1.1.1t.tar.gz
          tar xzf openssl-1.1.1t.tar.gz
          cd openssl-1.1.1t
          # 使用标准配置，但添加必要的include目录
          CFLAGS="-I/usr/local/musl/include" CC=musl-gcc ./Configure no-shared no-async --prefix=/usr/local/musl --openssldir=/usr/local/musl/ssl linux-x86_64
          make -j$(nproc)
          sudo make install
          
      - name: 编译Linux静态二进制文件
        env:
          OPENSSL_DIR: /usr/local/musl
          OPENSSL_STATIC: 1
          OPENSSL_INCLUDE_DIR: /usr/local/musl/include
          OPENSSL_LIB_DIR: /usr/local/musl/lib
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          
      - name: 上传Linux构建产物
        uses: actions/upload-artifact@v4
        with:
          name: lokipool-linux-x86_64
          path: target/x86_64-unknown-linux-musl/release/lokipool

  build-windows:
    name: 构建Windows二进制文件
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 安装Rust工具链
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      
      - name: 安装OpenSSL
        run: |
          choco install openssl
          echo "OPENSSL_DIR=C:/Program Files/OpenSSL-Win64" >> $env:GITHUB_ENV
          echo "OPENSSL_LIB_DIR=C:/Program Files/OpenSSL-Win64/lib" >> $env:GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=C:/Program Files/OpenSSL-Win64/include" >> $env:GITHUB_ENV
      
      - name: 编译Windows二进制文件
        run: cargo build --release
        
      - name: 上传Windows构建产物
        uses: actions/upload-artifact@v4
        with:
          name: lokipool-windows-x86_64
          path: target/release/lokipool.exe

  build-macos:
    name: 构建macOS二进制文件
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    steps:
      - uses: actions/checkout@v4
      
      - name: 安装Rust工具链
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          
      - name: 安装OpenSSL
        run: brew install openssl@1.1
        
      - name: 设置OpenSSL环境变量
        run: |
          echo "OPENSSL_DIR=$(brew --prefix openssl@1.1)" >> $GITHUB_ENV
          
      - name: 编译macOS二进制文件
        run: cargo build --release --target ${{ matrix.target }}
        
      - name: 上传macOS构建产物
        uses: actions/upload-artifact@v4
        with:
          name: lokipool-macos-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/lokipool

  create-release:
    name: 创建GitHub Release
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: 下载所有构建产物
        uses: actions/download-artifact@v4
        
      - name: 准备发布文件
        run: |
          mkdir -p release-artifacts
          mv lokipool-linux-x86_64/lokipool release-artifacts/lokipool-linux-x86_64
          mv lokipool-windows-x86_64/lokipool.exe release-artifacts/lokipool-windows-x86_64.exe
          mv lokipool-macos-x86_64-apple-darwin/lokipool release-artifacts/lokipool-macos-x86_64
          mv lokipool-macos-aarch64-apple-darwin/lokipool release-artifacts/lokipool-macos-arm64
          chmod +x release-artifacts/*
          
      - name: 创建GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-artifacts/lokipool-linux-x86_64
            release-artifacts/lokipool-windows-x86_64.exe
            release-artifacts/lokipool-macos-x86_64
            release-artifacts/lokipool-macos-arm64
